### ISSUE TITLE
bpy_struct: attribute "normal" from "MeshVertex" is read-only

### ISSUE THREAD

**Issue by elemich** [Puxtril/CSV-Import#3]
i inputed a csv exported from renderDoc, blender is version 3.4.1

full error:

Python: Traceback (most recent call last):
  File "C:\Users\Michele\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ImportCSV.py", line 351, in execute
    meshObj = createMesh(
  File "C:\Users\Michele\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\ImportCSV.py", line 541, in createMesh
    mesh.vertices[vertexIndex].normal = curNormalNorm
AttributeError: bpy_struct: attribute "normal" from "MeshVertex" is read-only

**Comment by Puxtril** [comment]
I just pushed an update to the repository, this issue has been fixed.
